name: Publish

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Install Node and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Remove root editorconfig
        shell: pwsh
        run: |
          Remove-Item .editorconfig -Force -ErrorAction SilentlyContinue

      - name: Install dependencies
        run: npm install

      - name: Package and publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --publish always --win
